### ISSUE TITLE
Support non `secret` KV2s

### ISSUE THREAD

**Issue by tiferrei** [RichiCoder1/vault-action#4]
Hi, currently the action only supports accessing secrets in the `secret` KV2 engine.
This is due to this line: https://github.com/RichiCoder1/vault-action/blob/da9a93f3f5bec24febf304139a6cbe61f0f8ad5e/action.js#L14

This is because the API URL for, for example, a KV called `ci` in an `ops` folder in the `secret` engine would be `/v1/secret/data/ops/ci`. However, if you have a different KV secret, for example one called `stage-secret` the URL would be `/v1/stage-secret/data/ops/ci`.

As such, as it is the action only supports querying the default KV engine. 

This isn't currently a blocker for me personally, just more of an FYI.

**Comment by RichiCoder1** [comment]
Yup, I built this with a pretty restricted feature scope. I'm open to expanding the scope of the action or accepting PRs if there's demand.

**Comment by RichiCoder1** [comment]
https://github.com/RichiCoder1/vault-action/pull/12 once merged will close this out (I believe).

**Comment by RichiCoder1** [comment]
This should now be supported in v0.5.0!
