### ISSUE TITLE
[FEAT] Support TLS Vault servers

### ISSUE THREAD

**Issue by jasonodonnell** [RichiCoder1/vault-action#85]
**Is your feature request related to a problem? Please describe.**
Hi from HashiCorp!  Testing this GitHub action against a Vault server protected by SSL.  The action cannot verify the server certificate because there's no way of configure a CA path and/or `tls-skip-verify`.

Error from build: `unable to verify the first certificate`

**Describe the solution you'd like**
Additional parameters should be added to support TLS:
- `vaultCA`: Path to certificate for the client to verify the server's certificate
- `tlsSkipVerify`: Optionally disable verification of the server (not recommended but useful for test)
- `clientKey`: Path to a client key used for mTLS
- `clientCert`: Path to a client certificate used for mTLS

**Describe alternatives you've considered**
TLS really needs to be supported, so I don't think there's other alternatives.

**Comment by RichiCoder1** [comment]
Did you find a solution or are you planning to re-open this separately post-transition? I'm pretty sure this is indeed not supported still.

**Comment by jasonodonnell** [comment]
I'm adding support for it now.  I think transition will be one of the last steps so I'll likely open a PR here to add the feature.

**Comment by RichiCoder1** [comment]
Sounds good! Let me know if you have any questions. Only possible change I'd make is supporting base64'd version of each `Path to` argument so people can use certs direct from secrets rather than having to write them out first.

**Comment by jasonodonnell** [comment]
@RichiCoder1 We're ready to transfer the repo when you are. Let us know when you want to make it happen.
